version: '3.8'

services:
  scylladb:
    image: scylladb/scylla:5.4
    container_name: scylladb-ultra-performance
    ports:
      - "9042:9042"  # CQL port
      - "9160:9160"  # Thrift port (legacy)
      - "7000:7000"  # Inter-node communication
      - "7001:7001"  # TLS inter-node communication
      - "9180:9180"  # Prometheus monitoring
    volumes:
      - scylla_data:/var/lib/scylla
      - ./scylla-config:/etc/scylla
    environment:
      - SCYLLA_CLUSTER_NAME=ultra-performance-cluster
      - SCYLLA_ENDPOINT_SNITCH=SimpleSnitch
      - SCYLLA_DC=datacenter1
      - SCYLLA_RACK=rack1
    command: >
      --seeds=scylladb
      --smp=2
      --memory=2G
      --overprovisioned=1
      --api-address=0.0.0.0
      --listen-address=0.0.0.0
      --rpc-address=0.0.0.0
      --broadcast-address=127.0.0.1
      --broadcast-rpc-address=127.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - scylla-network

  # ScyllaDB Monitoring (optional)
  scylla-monitoring:
    image: scylladb/scylla-monitoring:4.6
    container_name: scylla-monitoring
    ports:
      - "3000:3000"   # Grafana
      - "9090:9090"   # Prometheus
    volumes:
      - monitoring_data:/var/lib/grafana
      - ./monitoring-config:/etc/scylla-monitoring
    environment:
      - SCYLLA_NODES=scylladb:9180
    depends_on:
      scylladb:
        condition: service_healthy
    networks:
      - scylla-network
    profiles:
      - monitoring

volumes:
  scylla_data:
    driver: local
  monitoring_data:
    driver: local

networks:
  scylla-network:
    driver: bridge