{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "media-service.fullname" . }}
  labels:
    {{- include "media-service.labels" . | nindent 4 }}
spec:
  host: {{ include "media-service.fullname" . }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
{{- end }}