version: '3.8'

services:
  ultra-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./config:/etc/ultra-cpp:ro
      - /dev/hugepages:/dev/hugepages
    privileged: true  # Required for DPDK
    environment:
      - ULTRA_CONFIG_FILE=/etc/ultra-cpp/ultra-cpp.conf
    depends_on:
      - redis
      - prometheus
    networks:
      - ultra-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ultra-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - ultra-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ultra-network

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  ultra-network:
    driver: bridge