{{- if and .Values.workers.media-processor.enabled .Values.workers.media-processor.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "worker-service.fullname" . }}-media-processor
  labels:
    {{- include "worker-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: media-processor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "worker-service.fullname" . }}-media-processor
  minReplicas: {{ .Values.workers.media-processor.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workers.media-processor.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.workers.media-processor.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.workers.media-processor.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.workers.media-processor.autoscaling.customMetrics }}
    {{- toYaml .Values.workers.media-processor.autoscaling.customMetrics | nindent 4 }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 10
        periodSeconds: 60
      selectPolicy: Max
{{- end }}