apiVersion: v2
name: api-service
description: A Helm chart for the API service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"

keywords:
  - api
  - nodejs
  - express

maintainers:
  - name: Platform Team
    email: platform@company.com

annotations:
  category: Application