replicaCount: 5

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/api-service
  tag: "v1.0.0"

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: database-secret
        key: url
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: url
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: jwt-secret
        key: secret
  - name: AWS_REGION
    value: "us-east-1"

istio:
  enabled: true
  virtualService:
    enabled: true
    hosts:
      - api.company.com
    http:
      - match:
        - uri:
            prefix: /api/v1
        route:
        - destination:
            host: api-service
            port:
              number: 80
        fault:
          delay:
            percentage:
              value: 0.1
            fixedDelay: 5s
        retries:
          attempts: 3
          perTryTimeout: 10s
          retryOn: 5xx,reset,connect-failure,refused-stream