workers:
  media-processor:
    enabled: true
    replicaCount: 10
    image:
      repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/media-worker
      tag: "v1.0.0"
    resources:
      limits:
        cpu: 4000m
        memory: 8Gi
      requests:
        cpu: 2000m
        memory: 4Gi
    autoscaling:
      enabled: true
      minReplicas: 5
      maxReplicas: 100
      targetCPUUtilizationPercentage: 60
      customMetrics:
        - type: External
          external:
            metric:
              name: sqs_messages_visible
              selector:
                matchLabels:
                  queue_name: media-processing-production
            target:
              type: AverageValue
              averageValue: "3"
    nodeSelector:
      workload-type: media-processing
      instance-type: memory-optimized
    tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "media-processing"
        effect: "NoSchedule"

  outbox-processor:
    enabled: true
    replicaCount: 5
    image:
      repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/outbox-worker
      tag: "v1.0.0"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 20
      targetCPUUtilizationPercentage: 70

  data-export:
    enabled: true
    replicaCount: 3
    image:
      repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/data-export-worker
      tag: "v1.0.0"
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70

env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"
  - name: AWS_REGION
    value: "us-east-1"
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: redis-secret
        key: url
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: database-secret
        key: url